quarkus.http.host=0.0.0.0
quarkus.http.port=${PORT:8081}
quarkus.devservices.enabled=false

quarkus.datasource.db-kind=oracle
quarkus.datasource.jdbc.url=${DB_URL}
quarkus.datasource.username=${DB_USER}
quarkus.datasource.password=${DB_PASS}

quarkus.http.cors.origins=https://vision-tech-platform.vercel.app,http://localhost:5173
quarkus.http.cors.methods=GET,POST,PUT,DELETE,OPTIONS
quarkus.http.cors.headers=accept, authorization, content-type, x-requested-with
quarkus.datasource.jdbc.max-size=2
quarkus.datasource.jdbc.min-size=1

#Codigo para envio do email para criacao de senha
quarkus.mailer.from=visiontdb@gmail.com
quarkus.mailer.host=smtp.gmail.com
quarkus.mailer.port=587
quarkus.mailer.start-tls=REQUIRED
quarkus.mailer.username=visiontdb@gmail.com
quarkus.mailer.password=${EMAIL_VISION_PASSWORD}

quarkus.mailer.mock=true